theme: jekyll-theme-slate
title: Dry Herb Vape Discord Communities
description: "Discord communites for dry herb vapes (and dabs)"
domain: beyondcombustion.net       # if you want to force HTTPS, specify the domain without the http at the start, e.g. example.com
url: https://beyondcombustion.net  # the base hostname and protocol for your site, e.g. http://example.com
# Your name, as you want it to appear underneath each post and in the footer
author: ProfessionalHandJob

# Your email if you want it to be linked on the contact page
author_email: admin@beyondcombustion.net

category_dir: /

search: true

show_date: true
date_format: "%Y-%m-%d"

permalink: pretty

# plugins:
#- jekyll-paginate
#- jekyll-sitemap
#- jekyll-gist
#- jekyll-feed
#- jemoji
#- jekyll-include-cache
#- jekyll-remote-theme
#paginate: 15
